WARNING 2023-12-03 11:24:00,653 log Not Found: /inquiry3/
WARNING 2023-12-03 12:15:04,726 log Not Found: /.well-known/traffic-advice
WARNING 2023-12-03 12:27:28,177 log Not Found: /robots.txt
WARNING 2023-12-03 12:28:42,101 log Not Found: /robots.txt
WARNING 2023-12-03 12:29:58,916 log Not Found: /inquiry3/
DEBUG 2023-12-03 12:33:38,910 base Exception while resolving variable 'recaptcha_site_key' in template 'basecamp/inquiry1.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [recaptcha_site_key] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: '5HRjvmot9moWCnt2buWWKSzQINE9Syax4WA3BJGcd1VpRgT6LvJp8OkbQq2OJUlV'>, 'request': <WSGIRequest: POST '/price_detail/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fb7dac07240>>, 'perms': PermWrapper(<SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fb7dac07240>>), 'messages': <FallbackStorage: request=<WSGIRequest: POST '/price_detail/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'flight_date': '2023-12-23', 'direction': 'Drop off to Intl Airport', 'suburb': 'Brookvale', 'no_of_passenger': '1'}, {'block': <Block Node: content. Contents: [<TextNode: '\n      <!-- Page content-'>, <Variable Node: flight_date>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: direction>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: suburb>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: no_of_passenger>, <TextNode: '</a> -->\n\t\t\t  <br><br>\n  '>, <django.template.defaulttags.CsrfTokenNode object at 0x7fb7da852d90>, <TextNode: '\n\t\t\t\t<div class="mb3 pb-1'>, <Variable Node: direction>, <TextNode: '">'>, <Variable Node: direction>, <TextNode: '</option>\t\t\t\t\t\t          '>, <Variable Node: flight_date>, <TextNode: '" type="text" >\t\t\t\t  \n   '>, <IfNode>, <TextNode: '\n\t\t\t\t  <div class="mb-3 p'>, <Variable Node: suburb>, <TextNode: '</label>\t\t\t\t\t\n\t\t\t\t</div>\n'>, <Variable Node: suburb>, <TextNode: '">'>, <Variable Node: suburb>, <TextNode: '</option>\t\t\t\t\t\n\t\t\t\t  </se'>, <Variable Node: no_of_passenger>, <TextNode: '">'>, <Variable Node: no_of_passenger>, <TextNode: '</option>\t\t\t\t  \n         '>, <Variable Node: recaptcha_site_key>, <TextNode: '"></div>\n\t\t\t\t<div id="err'>]>}]
WARNING 2023-12-03 13:02:40,819 log Not Found: /robots.txt
WARNING 2023-12-03 13:10:12,019 log Not Found: /product/moncler-vest-for-women-smooth-shiny-fabric-black-2/
DEBUG 2023-12-03 13:16:51,840 base Exception while resolving variable 'recaptcha_site_key' in template 'basecamp/inquiry1.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'recaptcha_site_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [recaptcha_site_key] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'zFxZxrIQd5E99fAgV6uFrHAztNjMPUSTZcdk7dJIWXYscoj1bZFH5UcRWTmxNfuB'>, 'request': <WSGIRequest: POST '/price_detail/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fb7dac618a0>>, 'perms': PermWrapper(<SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fb7dac618a0>>), 'messages': <FallbackStorage: request=<WSGIRequest: POST '/price_detail/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'flight_date': '2023-12-04', 'direction': 'Drop off to Domestic Airport', 'suburb': 'Surry Hills', 'no_of_passenger': '2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n      <!-- Page content-'>, <Variable Node: flight_date>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: direction>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: suburb>, <TextNode: '</a><br>\n\t\t\t  <a style="f'>, <Variable Node: no_of_passenger>, <TextNode: '</a> -->\n\t\t\t  <br><br>\n  '>, <django.template.defaulttags.CsrfTokenNode object at 0x7fb7da5f8350>, <TextNode: '\n\t\t\t\t<div class="mb3 pb-1'>, <Variable Node: direction>, <TextNode: '">'>, <Variable Node: direction>, <TextNode: '</option>\t\t\t\t\t\t          '>, <Variable Node: flight_date>, <TextNode: '" type="text" >\t\t\t\t  \n   '>, <IfNode>, <TextNode: '\n\t\t\t\t  <div class="mb-3 p'>, <Variable Node: suburb>, <TextNode: '</label>\t\t\t\t\t\n\t\t\t\t</div>\n'>, <Variable Node: suburb>, <TextNode: '">'>, <Variable Node: suburb>, <TextNode: '</option>\t\t\t\t\t\n\t\t\t\t  </se'>, <Variable Node: no_of_passenger>, <TextNode: '">'>, <Variable Node: no_of_passenger>, <TextNode: '</option>\t\t\t\t  \n         '>, <Variable Node: recaptcha_site_key>, <TextNode: '"></div>\n\t\t\t\t<div id="err'>]>}]
WARNING 2023-12-03 13:55:30,219 log Not Found: /robots.txt
WARNING 2023-12-03 13:55:31,195 log Not Found: /shop/product/moncler-bady-2/
WARNING 2023-12-03 14:05:36,150 log Not Found: /RDWeb/Pages/en-US/login.aspx
WARNING 2023-12-03 14:18:58,968 log Not Found: /robots.txt
WARNING 2023-12-03 14:19:00,625 log Not Found: /sitemap.xml
WARNING 2023-12-03 14:19:04,304 log Not Found: /sitemap_index.xml
WARNING 2023-12-03 14:19:12,096 log Not Found: /sitemap1.xml
WARNING 2023-12-03 14:43:10,127 log Not Found: /wp-content/themes/famous/megaframe/megapanel/inc/functions.php
WARNING 2023-12-03 14:43:36,048 log Not Found: /robots.txt
WARNING 2023-12-03 14:44:15,720 log Not Found: /robots.txt
WARNING 2023-12-03 14:54:49,421 log Not Found: /robots.txt
WARNING 2023-12-03 14:58:25,140 log Not Found: /robots.txt
ERROR 2023-12-03 15:00:17,805 log Internal Server Error: /paypal_ipn/
DEBUG 2023-12-03 15:09:36,246 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Sajid', 'contact': '0470334832', 'email': 'Sajidkv@gmail.com', 'flight_date': datetime.date(2023, 12, 19), 'flight_number': 'Sq233', 'flight_time': '12:15', 'pickup_time': '08:00', 'direction': 'Drop off to Intl Airport', 'street': '203/8 Hannah street', 'suburb': 'Westmead', 'no_of_passenger': '4', 'no_of_baggage': '4', 'return_direction': None, 'return_flight_date': None, 'return_flight_number': None, 'return_flight_time': None, 'return_pickup_time': None, 'message': '', 'price': '120', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:10:31,820 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Anna severino', 'contact': '0402015239', 'email': 'mentor2122@optusnet.com.au', 'flight_date': datetime.date(2023, 12, 31), 'flight_number': 'Qf101', 'flight_time': '08:35', 'pickup_time': '05:00', 'direction': 'Drop off to Intl Airport', 'street': '8 Darcy St', 'suburb': 'Marsfield', 'no_of_passenger': '7', 'no_of_baggage': '6', 'return_direction': 'Pickup from Intl Airport', 'return_flight_date': datetime.date(2024, 1, 7), 'return_flight_number': 'Qf5542', 'return_flight_time': '19:50', 'return_pickup_time': '19:50', 'message': 'Need a baby car seat for a 4 month', 'price': '300', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:11:00,926 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Gabriel', 'contact': '0402792982', 'email': 'gabriel.prasad@gmail.com', 'flight_date': datetime.date(2023, 12, 18), 'flight_number': 'Fj910', 'flight_time': '14:00', 'pickup_time': '10:00', 'direction': 'Drop off to Intl Airport', 'street': '29 Bardia road', 'suburb': 'Carlingford', 'no_of_passenger': '4', 'no_of_baggage': '4', 'return_direction': 'Pickup from Intl Airport', 'return_flight_date': datetime.date(2024, 1, 12), 'return_flight_number': 'FJ911', 'return_flight_time': '12:30', 'return_pickup_time': '13:00', 'message': '', 'price': '250', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:11:59,916 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Bobby', 'contact': '0431240784', 'email': 'daeibabak@yahoo.com', 'flight_date': datetime.date(2023, 12, 9), 'flight_number': 'jq27', 'flight_time': '15:05', 'pickup_time': '11:15', 'direction': 'Drop off to Intl Airport', 'street': '290 Burns Bay Rd', 'suburb': 'Lane Cove', 'no_of_passenger': '4', 'no_of_baggage': '4', 'return_direction': None, 'return_flight_date': None, 'return_flight_number': None, 'return_flight_time': None, 'return_pickup_time': None, 'message': 'Hi there,\r\nWe are two adult two kids and have 4 check-in luggage and 4 carry-on bag. Please provide us with a quotation\r\n\r\nRegards', 'price': '105', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:12:46,159 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Fed', 'contact': '0433222562', 'email': 'fedsnew@gmail.com', 'flight_date': datetime.date(2023, 12, 14), 'flight_number': 'Ga715', 'flight_time': '10:00', 'pickup_time': '07:00', 'direction': 'Drop off to Intl Airport', 'street': '10/42 cliff rd', 'suburb': 'Epping', 'no_of_passenger': '4', 'no_of_baggage': '5', 'return_direction': None, 'return_flight_date': None, 'return_flight_number': None, 'return_flight_time': None, 'return_pickup_time': None, 'message': 'Hi we have 3 large luggage\r\n3x small i need to be in airport by 8am', 'price': '120', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:14:27,700 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'SUNG KAM', 'contact': '0406883355', 'email': 'sungkam718@gmail.com', 'flight_date': datetime.date(2023, 12, 15), 'flight_number': 'QF644', 'flight_time': '09:00', 'pickup_time': '14:00', 'direction': 'Drop off to Intl Airport', 'street': '1/6-12 SINCLAIR AVE', 'suburb': 'Thornleigh', 'no_of_passenger': '1', 'no_of_baggage': '2', 'return_direction': None, 'return_flight_date': None, 'return_flight_number': None, 'return_flight_time': None, 'return_pickup_time': None, 'message': '', 'price': '240', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:16:21,641 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Peter Kam', 'contact': '450035664', 'email': 'sungkam3@gmail.com', 'flight_date': datetime.date(2023, 12, 7), 'flight_number': 'Sq231', 'flight_time': '18:13', 'pickup_time': '19:30', 'direction': 'Drop off to Domestic Airport', 'street': 'Unit 715/15 Barton Road', 'suburb': 'Auburn', 'no_of_passenger': '1', 'no_of_baggage': '2', 'return_direction': 'Pickup from Intl Airport', 'return_flight_date': datetime.date(2023, 12, 30), 'return_flight_number': 'CX101', 'return_flight_time': '18:00', 'return_pickup_time': '20:00', 'message': '', 'price': '180', 'notice': '', 'private_ride': False}]
DEBUG 2023-12-03 15:16:43,420 base Exception while resolving variable 'email1' in template 'basecamp/html_email-inquiry-response.html'.
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'email1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [email1] in [{'True': True, 'False': False, 'None': None}, {'company_name': '', 'name': 'Peter Kam', 'contact': '450035664', 'email': 'sungkam3@gmail.com', 'flight_date': datetime.date(2023, 12, 7), 'flight_number': 'Sq231', 'flight_time': '18:13', 'pickup_time': '19:30', 'direction': 'Drop off to Domestic Airport', 'street': 'Unit 715/15 Barton Road', 'suburb': 'Auburn', 'no_of_passenger': '1', 'no_of_baggage': '2', 'return_direction': 'Pickup from Intl Airport', 'return_flight_date': datetime.date(2023, 12, 30), 'return_flight_number': 'CX101', 'return_flight_time': '18:00', 'return_pickup_time': '20:00', 'message': '', 'price': '180', 'notice': '', 'private_ride': False}]
WARNING 2023-12-03 15:37:34,107 log Not Found: /.well-known/acme-challenge/0WEOJ87V-S89K-SAZJEBXPPMRN_G5HX9
WARNING 2023-12-03 15:37:35,077 log Not Found: /.well-known/acme-challenge/1A9LPJ1_MP4YDC7IHI56N9XM34NZ3613
WARNING 2023-12-03 15:40:23,644 log Not Found: /wp-content/themes/include.php
WARNING 2023-12-03 15:40:30,676 log Not Found: /wp-content/plugins/WordPressCore/include.php
WARNING 2023-12-03 15:40:35,486 log Not Found: /wp-content/themes/sketch/404.php
WARNING 2023-12-03 15:40:45,348 log Not Found: /wp-content/plugins/core-plugin/include.php
WARNING 2023-12-03 15:40:53,552 log Not Found: /wp-includes/widgets/include.php
WARNING 2023-12-03 15:40:59,222 log Not Found: /wp-content/include.php
WARNING 2023-12-03 15:41:08,862 log Not Found: /wp-content/themes/twentyfive/include.php
WARNING 2023-12-03 15:41:29,482 log Not Found: /wp-includes/images/include.php
WARNING 2023-12-03 15:41:36,442 log Not Found: /wp-content/plugins/include.php
