WARNING 2023-11-26 08:20:58,686 log Not Found: /shop/de/product/moncler-jacken-manner-zin-schwarz/
ERROR 2023-11-26 09:06:53,385 log Internal Server Error: /confirmation_detail/
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/basecamp/views.py", line 1144, in confirmation_detail
    p.save()
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/blog/signals.py", line 225, in create_event_on_calendar
    instance.save()
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/blog/signals.py", line 217, in create_event_on_calendar
    event = service.events().update(calendarId='primary', eventId=instance.calendar_event_id, body=event).execute()
            ^^^^^^^
UnboundLocalError: cannot access local variable 'service' where it is not associated with a value
ERROR 2023-11-26 09:10:42,414 log Internal Server Error: /confirmation_detail/
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/basecamp/views.py", line 1144, in confirmation_detail
    p.save()
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/blog/signals.py", line 223, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
            ^^^^^^^
UnboundLocalError: cannot access local variable 'service' where it is not associated with a value
ERROR 2023-11-26 09:15:19,836 log Internal Server Error: /confirmation_detail/
Traceback (most recent call last):
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/basecamp/views.py", line 1144, in confirmation_detail
    p.save()
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/home/horeb/github/easygo/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horeb/github/easygo/blog/signals.py", line 223, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
            ^^^^^^^
UnboundLocalError: cannot access local variable 'service' where it is not associated with a value
WARNING 2023-11-26 09:17:49,256 log Not Found: /inquiry_done
